### ISSUE TITLE
NameError: name 'log' is not defined 

### ISSUE THREAD

**Issue by Oguz-Kagan-71** [ttdennis/bluetooth_smp_pocs#1]
─$ python smp_bruteforce.py 64:48:fc:37:35:82
[!] Found 1 HCI devices via ioctl(HCIGETDEVLIST)!
[*] HCI device: hci0  [11:22:33:44:55:66]  flags=5<UP RUNNING>
[!] Found 1 HCI devices via ioctl(HCIGETDEVLIST)!
[*] HCI device: hci0  [11:22:33:44:55:66]  flags=5<UP RUNNING>
[ERROR] Unable to bind
[*] Connected to hci0
[!] Receive Thread started.
[!] Send Thread started.
[!] _sendThreadFunc: No response from the firmware.
[!] sendHciCommand: waiting for response timed out!
[!] initialize_fimware: Failed to send a HCI command to the Bluetooth driver.
            adb: Check if you installed a custom bluetooth.default.so properly on your
              Android device. bluetooth.default.so must contain the string 'hci_inject'.
            hci: You might have insufficient permissions to send this type of command.
[!] connect: Failed to initialize firmware!
Traceback (most recent call last):
  File "/home/kali/Downloads/bluetooth_smp_pocs/smp_bruteforce/smp_bruteforce.py", line 216, in <module>
    main()
  File "/home/kali/Downloads/bluetooth_smp_pocs/smp_bruteforce/smp_bruteforce.py", line 205, in main
    log.critical("No connection to internalblue device.")
NameError: name 'log' is not defined 
how can ı fix

**Comment by ttdennis** [comment]
Ah, the `NameError: name 'log' is not defined` error is due to a mistake in the code, I just fixed that.

But it seems that internalblue is not able to talk to you Bluetooth chip. Do you have a compatible device? (see https://github.com/seemoo-lab/internalblue/blob/master/doc/setup.md). In a VM you need to make sure the device is properly forwarded.

For this setup I just bought a Bluetooth USB stick that I forwarded into the VM, but I had to try multiple ones until I found one that was compatible with Linux and was able to communicate over H4/HCI (which is what internalblue does).

**Comment by Oguz-Kagan-71** [comment]
thx your feedback , ı have CSR V4.0 bluetooth dongle.  ı installed ınternalblue , pycryptodome and pwntools. which device is compatible , ı will buy it.  Except that could there be any other problem besides the bluetooth chip I'm using? etc. related to python.

**Comment by Oguz-Kagan-71** [comment]
└─$ sudo python smp_bruteforce.py 56:a4:78:7a:0b:50       

dpkg-query: no path found matching pattern *bin/armeabi*linux*-as*
Could not find 'as' installed for ContextType(arch = 'thumb', bits = 32, endian = 'little')
Try installing binutils for this architecture:
https://docs.pwntools.com/en/stable/install/binutils.html
[!] pwnlib.asm.which_binutils() cannot find 'as'!
[!] pwntools cannot find binutils for arm architecture. Disassembling will not work!
[!] Found 1 HCI devices via ioctl(HCIGETDEVLIST)!
[*] HCI device: hci0  [77:22:34:44:55:77]  flags=5<UP RUNNING>
[!] Found 1 HCI devices via ioctl(HCIGETDEVLIST)!
[*] HCI device: hci0  [77:22:34:44:55:77]  flags=5<UP RUNNING>
[ERROR] Unable to bind
[*] Connected to hci0
[!] Receive Thread started.
[!] Send Thread started.
[!] _sendThreadFunc: No response from the firmware.
[!] sendHciCommand: waiting for response timed out!
[!] initialize_fimware: Failed to send a HCI command to the Bluetooth driver.
            adb: Check if you installed a custom bluetooth.default.so properly on your
              Android device. bluetooth.default.so must contain the string 'hci_inject'.
            hci: You might have insufficient permissions to send this type of command.
[!] connect: Failed to initialize firmware!
CRITICAL:root:No connection to internalblue device.

**Comment by Oguz-Kagan-71** [comment]
└─$ sudo python smp_bruteforce.py 56:a4:78:7a:0b:50       

dpkg-query: no path found matching pattern *bin/armeabi*linux*-as*
Could not find 'as' installed for ContextType(arch = 'thumb', bits = 32, endian = 'little')
Try installing binutils for this architecture:
https://docs.pwntools.com/en/stable/install/binutils.html
[!] pwnlib.asm.which_binutils() cannot find 'as'!
[!] pwntools cannot find binutils for arm architecture. Disassembling will not work!
[!] Found 1 HCI devices via ioctl(HCIGETDEVLIST)!
[*] HCI device: hci0  [77:22:34:44:55:77]  flags=5<UP RUNNING>
[!] Found 1 HCI devices via ioctl(HCIGETDEVLIST)!
[*] HCI device: hci0  [77:22:34:44:55:77]  flags=5<UP RUNNING>
[ERROR] Unable to bind
[*] Connected to hci0
[!] Receive Thread started.
[!] Send Thread started.
[!] _sendThreadFunc: No response from the firmware.
[!] sendHciCommand: waiting for response timed out!
[!] initialize_fimware: Failed to send a HCI command to the Bluetooth driver.
            adb: Check if you installed a custom bluetooth.default.so properly on your
              Android device. bluetooth.default.so must contain the string 'hci_inject'.
            hci: You might have insufficient permissions to send this type of command.
[!] connect: Failed to initialize firmware!
CRITICAL:root:No connection to internalblue device.

**Comment by Oguz-Kagan-71** [comment]
└─$ sudo python smp_bruteforce.py 56:a4:78:7a:0b:50       

dpkg-query: no path found matching pattern *bin/armeabi*linux*-as*
Could not find 'as' installed for ContextType(arch = 'thumb', bits = 32, endian = 'little')
Try installing binutils for this architecture:
https://docs.pwntools.com/en/stable/install/binutils.html
[!] pwnlib.asm.which_binutils() cannot find 'as'!
[!] pwntools cannot find binutils for arm architecture. Disassembling will not work!
[!] Found 1 HCI devices via ioctl(HCIGETDEVLIST)!
[*] HCI device: hci0  [77:22:34:44:55:77]  flags=5<UP RUNNING>
[!] Found 1 HCI devices via ioctl(HCIGETDEVLIST)!
[*] HCI device: hci0  [77:22:34:44:55:77]  flags=5<UP RUNNING>
[ERROR] Unable to bind
[*] Connected to hci0
[!] Receive Thread started.
[!] Send Thread started.
[!] _sendThreadFunc: No response from the firmware.
[!] sendHciCommand: waiting for response timed out!
[!] initialize_fimware: Failed to send a HCI command to the Bluetooth driver.
            adb: Check if you installed a custom bluetooth.default.so properly on your
              Android device. bluetooth.default.so must contain the string 'hci_inject'.
            hci: You might have insufficient permissions to send this type of command.
[!] connect: Failed to initialize firmware!
CRITICAL:root:No connection to internalblue device.
